# Generated by Django 5.1.3 on 2024-11-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patent',
            name='priority_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patent',
            name='publ_date',
            field=models.DateField(),
        ),
    ]
