# Generated by Django 5.1.3 on 2024-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patent_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patent',
            name='grant_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patent',
            name='priority_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patent',
            name='publ_date',
            field=models.DateTimeField(),
        ),
    ]
