# Generated by Django 5.1.3 on 2024-11-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patent_creation_date_alter_patent_grant_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patent',
            name='id',
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
